### ISSUE TITLE
Plugins not working with manually-built magnum-examples

### ISSUE THREAD

**Issue by dyzdyz010** [mosra/homebrew-magnum#1]
I installed all taps:

```
brew install --HEAD mosra/magnum/corrade
brew install --HEAD mosra/magnum/magnum
brew install --HEAD mosra/magnum/magnum-plugins
brew install --HEAD mosra/magnum/magnum-integration
brew install --HEAD mosra/magnum/magnum-extras
```

Then build [magnum-examples](https://github.com/mosra/magnum-examples) manually using `cmake -G Xcode`, then open the generated Xcode project, run target `magnum-cubemap`, the console shows following error:

```
Renderer: AMD Radeon R9 M370X OpenGL Engine by ATI Technologies Inc.
OpenGL version: 4.1 ATI-1.66.31
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_vertex_array_object
    GL_EXT_debug_label
    GL_EXT_debug_marker
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
PluginManager::Manager::load(): plugin JpegImporter is not static and was not found in /usr/local/Cellar/magnum/HEAD-920db7a/lib/magnum/importers
Program ended with exit code: 1
```

I checked the directory mentioned, and there's only `.conf` and `.so` files, no static lib files:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1324420/38479442-c7ad3872-3bf1-11e8-97a5-8e71dccfae84.png">

ENV: macOS High Sierra 10.13.4, Xcode 9.2

**Comment by mosra** [comment]
Hi, thanks for the report! 

This looks like the plugins from `magnum-plugins` got installed in a wrong location. What does the following command show?

```sh
brew list magnum-plugins
```

**Comment by dyzdyz010** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1324420/38486449-a73a311c-3c0f-11e8-8089-ec441cc4f920.png">

**Comment by mosra** [comment]
Huh. I see. The assumption is that the `lib/magnum/` is shared by both `magnum` and `magnum-plugins` and ... well, the project got confused by Homebrew installing every package to a special directory.

Does `/usr/local/lib/magnum/` exist? What does the following show?

```sh
ls /usr/local/lib/magnum
```

If so, then fixing this should be just a matter of a simple patch to the main magnum formula like below. I'll push the update as soon as you confirm that the directory exists and contains all the plugins.

```diff
diff --git a/Formula/magnum.rb b/Formula/magnum.rb
index 3b41d88..436a8c1 100644
--- a/Formula/magnum.rb
+++ b/Formula/magnum.rb
@@ -13,7 +13,7 @@ class Magnum < Formula
   def install
     system "mkdir build"
     cd "build" do
-      system "cmake", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_INSTALL_PREFIX=#{prefix}", "-DWITH_AUDIO=ON", "-DWITH_GLFWAPPLICATION=OFF", "-DWITH_SDL2APPLICATION=ON", "-DWITH_WINDOWLESSCGLAPPLICATION=ON", "-DWITH_CGLCONTEXT=ON", "-DWITH_OPENGLTESTER=ON", "-DWITH_ANYAUDIOIMPORTER=ON", "-DWITH_ANYIMAGECONVERTER=ON", "-DWITH_ANYIMAGEIMPORTER=ON", "-DWITH_ANYSCENEIMPORTER=ON", "-DWITH_MAGNUMFONT=ON", "-DWITH_MAGNUMFONTCONVERTER=ON", "-DWITH_OBJIMPORTER=ON", "-DWITH_TGAIMAGECONVERTER=ON", "-DWITH_TGAIMPORTER=ON", "-DWITH_WAVAUDIOIMPORTER=ON", "-DWITH_DISTANCEFIELDCONVERTER=ON", "-DWITH_FONTCONVERTER=ON", "-DWITH_IMAGECONVERTER=ON", "-DWITH_MAGNUMINFO=ON", "-DWITH_AL_INFO=ON", ".."
+      system "cmake", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_INSTALL_PREFIX=#{prefix}", "-DMAGNUM_PLUGINS_DIR=#{HOMEBREW_PREFIX}/lib/magnum", "-DWITH_AUDIO=ON", "-DWITH_GLFWAPPLICATION=OFF", "-DWITH_SDL2APPLICATION=ON", "-DWITH_WINDOWLESSCGLAPPLICATION=ON", "-DWITH_CGLCONTEXT=ON", "-DWITH_OPENGLTESTER=ON", "-DWITH_ANYAUDIOIMPORTER=ON", "-DWITH_ANYIMAGECONVERTER=ON", "-DWITH_ANYIMAGEIMPORTER=ON", "-DWITH_ANYSCENEIMPORTER=ON", "-DWITH_MAGNUMFONT=ON", "-DWITH_MAGNUMFONTCONVERTER=ON", "-DWITH_OBJIMPORTER=ON", "-DWITH_TGAIMAGECONVERTER=ON", "-DWITH_TGAIMPORTER=ON", "-DWITH_WAVAUDIOIMPORTER=ON", "-DWITH_DISTANCEFIELDCONVERTER=ON", "-DWITH_FONTCONVERTER=ON", "-DWITH_IMAGECONVERTER=ON", "-DWITH_MAGNUMINFO=ON", "-DWITH_AL_INFO=ON", ".."
       system "cmake", "--build", "."
       system "cmake", "--build", ".", "--target", "install"
     end

```

Thank you!

**Comment by dyzdyz010** [comment]
Thanks for such a top speed response :P  It seems this directory exists and contains all plugins:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1324420/38492613-1a36ac06-3c22-11e8-8d33-567e28fa0bfa.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/1324420/38492623-23b2fb9a-3c22-11e8-914c-1b4ff4bb72c3.png">

**Comment by mosra** [comment]
I just pushed c08ce3ff7f01d58b1bd519ce2d946d18d4425b92 with the above patch. Can you

```sh
brew reinstall --HEAD mosra/magnum/magnum
```

and try the example again? Just reinstalling the core package should be enough, no need to do that for the others.

**Comment by dyzdyz010** [comment]
I reinstalled magnum as you said, re-cmaked the project, however the same error still comes up 😅

I noticed that it says the plugin needed(`JpegImporter`) is `not static`, so maybe it's because of magnum-plugins building settings? cuz in the screenshot I posted above shows only `.so` files in required location.

**Comment by mosra** [comment]
Huh. This is weird. Sorry. I am not keeping up with Homebrew core functionality changes, but it might now be that you have to call

```sh
brew update
```

in order to pick up the change I pushed (and then perform the `reinstall`). I'm pretty sure this was not required a year ago, but who knows.

> I noticed that it says the plugin needed (JpegImporter) is not static [...]

No, it should pick up the `*.so` file, static plugins are mainly a fallback option used on platforms with poor dlopen() support.

The magnum package should install the `magnum-imageconverter` tool, can you run it like this? If the following succeeds, then the example should work as well.

```sh
magnum-imageconverter some-jpeg-image-you-have.jpg output.png
```

In 6d0f47db4050815c21fbf25b33bf5a665e9ce715 I made a simple Travis CI setup to verify that the packages build correctly and the above works there. So I hope it was just the missing `brew update`.

**Comment by dyzdyz010** [comment]
Ah, sorry my fault, `brew update` and it works now, thank you so much!🎉

**Comment by mosra** [comment]
Great! Closing this then :)
