### ISSUE TITLE
 install magnum-plugins on Mac Catalina 10.15

### ISSUE THREAD

**Issue by xiviu123** [mosra/homebrew-magnum#3]
I tried to install magnum plugin by command "brew install --HEAD mosra/magnum/magnum-plugins".
Here is  error logs.

Scanning dependencies of target PngImageConverter
Scanning dependencies of target PngImporter
/tmp/magnum-plugins-20191016-23977-myermq/src/MagnumPlugins/JpegImporter/JpegImporter.cpp:101:5: error: use of undeclared identifier 'jpeg_mem_src'
    jpeg_mem_src(&file, _in.begin(), _in.size());
    ^
[ 53%] Building CXX object src/MagnumPlugins/PngImageConverter/CMakeFiles/PngImageConverter.dir/PngImageConverter.cpp.o
[ 55%] Building CXX object src/MagnumPlugins/PngImporter/CMakeFiles/PngImporter.dir/PngImporter.cpp.o
1 error generated.
make[2]: *** [src/MagnumPlugins/JpegImporter/CMakeFiles/JpegImporter.dir/JpegImporter.cpp.o] Error 1
make[1]: *** [src/MagnumPlugins/JpegImporter/CMakeFiles/JpegImporter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 57%] Linking CXX shared module ../../../Release/lib/magnum/imageconverters/MiniExrImageConverter.so
[ 57%] Built target MiniExrImageConverter
[ 60%] Linking CXX shared module ../../../Release/lib/magnum/imageconverters/PngImageConverter.so
[ 62%] Linking CXX shared module ../../../Release/lib/magnum/importers/PngImporter.so
[ 62%] Built target PngImageConverter
[ 62%] Built target PngImporter
make: *** [all] Error 2

pls help to fix, thank you.

**Comment by mosra** [comment]
Hi!

this looks like it picked up some old version of libjpeg that doesn't have `jpeg_mem_src()` defined (which is needed in order to load JPEGs from memory and not files), instead of `jpeg` from homebrew. 
In mosra/magnum-plugins@1f96038e0f361700dac60246c62a6aa653a8c26c I improved the error handling for this case, so now it should fail directly during the CMake configure step, telling you what library it found. Can you do `brew install --HEAD mosra/magnum/magnum-plugins` again and post the full build log? The CMake configure log, right before it exits, should have a line similar to this one:

```
-- Found JPEG: /usr/lib/libjpeg.so (found version "80") 
```

Thank you!

**Comment by xiviu123** [comment]
Hi, thank you for response.
`-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "62") 
CMake Error at src/MagnumPlugins/JpegImporter/CMakeLists.txt:34 (message):
  JpegImporter needs libjpeg version 80 but only 62 found, which doesn't have
  jpeg_mem_src()`
You are right, the latest version  of libjpeg is 62.

How can i link with custom libjpeg ?

**Comment by mosra** [comment]
Is this one coming from Homebrew? Or is it a file produced by something else? The plugins package depends on the `jpeg` package and Homebrew [seems to have version 9c already](https://formulae.brew.sh/formula/jpeg) -- and in my own tests it always picked up a recent-enough version.

What happens if you  `brew update && brew upgrade jpeg` and then try installing the plugins again?

**Comment by xiviu123** [comment]
> Homebrew seems to have version 9c already >  -- exactly, but it picked older libjpeg version. Could you add minimal version to 80 in cmake find_package function?

**Comment by mosra** [comment]
I'm afraid that won't help, only produce a slightly different error message. Looking at the FindJPEG module, CMake is not able to restart the search if a wrong version of libjpeg is found :/

Where is the library installed by Homebrew located? Do you *need* to have this old one as well? If you'd remove this one and keep only the version installed by Homebrew, it should work.

**Comment by xiviu123** [comment]
i've just check again, the jpeg installed location "/usr/local/Cellar/jpeg", and libjpeg  linked to ver 9. 
`libjpeg.dylib -> libjpeg.9.dylib`

![image](https://user-images.githubusercontent.com/2511113/66908262-fa4fa500-f034-11e9-9df6-02dcfecc5ca4.png)

the function `jpeg_mem_src` already exist too.
please revert https://github.com/mosra/magnum-plugins/commit/1f96038e0f361700dac60246c62a6aa653a8c26c, i will retry installing

**Comment by mosra** [comment]
I don't think the commit needs to be reverted -- it's just a check, if it finds a correct version of libjpeg, it won't complain.

But you need to remove the `/usr/local/libjpeg.dylib` and related headers and have Homebrew replace it with a symlink to `/usr/local/Cellar/jpeg/9c/libjpeg.dylib`. I'm not sure what's the command to do that -- `brew reinstall jpeg`? At the very least it should complain that some other `/usr/local/libjpeg.dylib` is there already and asking to replace those files.

**Comment by xiviu123** [comment]
hmm, seem to be the ploblem is resolved  with `brew reinstall jpeg`, but only when remove checking version of jpeg.

i got success with manual build 

please reverted the commit for other people. thank you.

**Comment by mosra** [comment]
This is strange -- it still fails with this message, even after a `brew reinstall`?

```
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "62") 
CMake Error at src/MagnumPlugins/JpegImporter/CMakeLists.txt:34 (message): 
  JpegImporter needs libjpeg version 80 but only 62 found, which doesn't have jpeg_mem_src()
```

**Comment by xiviu123** [comment]
i dont sure, but after  `brew reinstall` libjpeg version still is 62, and then i comment out check version block , work with manual build

**Comment by mosra** [comment]
Okay, then you probably still have some outdated `jconfig.h` somewhere that has `#define JPEG_LIB_VERSION 62` and CMake picks it up -- can you search for such a file on your filesystem?

**Comment by xiviu123** [comment]
JPEG_LIB_VERSION = 90 is defined in jpeglib.h not jconfig.h

**Comment by mosra** [comment]
Yeah ... but I'm looking for a file that defines it *wrong* -- is there no `jconfig.h` anywhere, defining the old version number?

**Comment by xiviu123** [comment]
currently i dont see , i  will find more and get back

**Comment by mosra** [comment]
Not even `jconfig62.h` or somesuch? Files starting with `jconfig`? For reference, this is where CMake looks: https://github.com/Kitware/CMake/blob/220d5995076f794e222c882963fb634169a6600b/Modules/FindJPEG.cmake#L71-L86

**Comment by mosra** [comment]
I got a report that this broke with Vcpkg `jpeg` packages as well (these report 62 too, apparently), so reverting that again in mosra/magnum-plugins@09980353c1bda8ecd6711dd797ab14ed80e13a13 -- too much problems and not really a solution to anything.

And since it works for you now, closing as done :)
